name: obstatil
description: "Engelliler için park şikayet uygulaması"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  go_router: ^12.1.1
  flutter_spinkit: ^5.2.0
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  geolocator: ^10.1.0
  path: ^1.8.3
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  sqflite: ^2.3.0
  logger: ^1.0.0
  # Firebase
  firebase_core: ^2.25.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/girisanimasyon.png
    - assets/images/google_logo.png
    - assets/icons/
    - assets/languages/
    - assets/motions/
