// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB']!,
    appId: '1:900490830678:web:8c7c2f2aa66c6ae4deacf7',
    messagingSenderId: '900490830678',
    projectId: 'obstatil-c5203',
    storageBucket: 'obstatil-c5203.appspot.com',
    authDomain: 'obstatil-c5203.firebaseapp.com',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID']!,
    appId: '1:900490830678:android:102588fb96bbef67deacf7',
    messagingSenderId: '900490830678',
    projectId: 'obstatil-c5203',
    storageBucket: 'obstatil-c5203.appspot.com',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS']!,
    appId: '1:900490830678:ios:8c7c2f2aa66c6ae4deacf7',
    messagingSenderId: '900490830678',
    projectId: 'obstatil-c5203',
    storageBucket: 'obstatil-c5203.appspot.com',
    iosClientId:
        '900490830678-4tbhm7pnot2c9kiqjksbtvvefbomu0bf.apps.googleusercontent.com',
    iosBundleId: 'com.obstatil.app',
  );
}
